name: docs to pdf

on:
  workflow_dispatch:
    inputs:
      document_name:
        description: 'the document to publish'
        required: true
        type: string

jobs:
  converttopdf:
    name: Build Pub PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install pandoc   
        run: sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
      
      - name: convert
        run: pandoc $WORKSPACE/pub/out/$DOCUMENT_NAME.md --pdf-engine=xelatex -o $DOCUMENT_NAME.pdf 
        env:
          DOCUMENT_NAME: ${{ inputs.document_name }}
          WORKSPACE: ${{ github.workspace }}
